SocialMedia/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import MessagesView, ChatRoomView

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('home/', views.home, name='home'),  
    path('signup/', views.signup, name='signup'),
    path('send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<int:request_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('friend_requests/', views.friend_requests, name='friend_requests'),
    path('create_post/', views.create_post, name='create_post'),
    path('profile/<str:username>/', views.profile_view, name='profile_view'),
    path('profile/update/<str:username>/', views.update_profile, name='update_profile'),
    path('logout/', views.user_logout, name='logout'),
    path('post/delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('update/username/<str:username>/', views.update_username, name='update_username'),
    path('update/pronouns/<str:username>/', views.update_pronouns, name='update_pronouns'),
    path('update/bio/<str:username>/', views.update_bio, name='update_bio'),
    path('unfriend/<int:user_id>/', views.unfriend_view, name='unfriend'),
    path('friends/', views.friends_view, name='friends'),
    path('like/<int:pk>/', views.like_post, name='like_post'),
    
    path('shorts/', views.shorts_view, name='shorts_view'),
    path('upload/', views.upload_view, name='upload'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    # path('create-card/', views.create_card, name='create_card'),
    path('cards/', views.cards_view, name='cards'),  # For logged-in user
    path('cards/<str:username>/', views.other_user_cards_view, name='user_cards'),
    # MESSAGING

    path('messages/', MessagesView.as_view(), name='messages'),
    path('chat/<str:username>/', ChatRoomView.as_view(), name='chat_room'),
    path('bookmarks/', views.bookmarks_view, name='bookmarks'),
    path('toggle-bookmark/', views.toggle_bookmark, name='toggle_bookmark'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/login/', permanent=False)),  # Redirect root to login
    path('', include('SocialMedia.urls')),
]

SocialMedia/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, related_name='sent_requests', on_delete=models.CASCADE)
    reciever = models.ForeignKey(User, related_name='recieved_requests', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Friendship(models.Model):
    user1 = models.ForeignKey(User, related_name='friend1', on_delete=models.CASCADE)
    user2 = models.ForeignKey(User, related_name='friend2', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

# Post for home page
    
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    is_short = models.BooleanField(default=False) 

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.content[:20]
    

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="Anonymous")
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}: {self.body[:20]}'
    


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bookmarks")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="bookmarked_by")
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'post')  # Ensure that a post is bookmarked only once by the same user

    def __str__(self):
        return f"{self.user.username} bookmarked {self.post.title}"

    def get_absolute_url(self):
        return reverse('bookmarks')

# Profile Picture
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', default='images/default.png', blank=True, null=True)
    pronouns = models.CharField(max_length=50, blank=True)  # Add this line
    bio = models.TextField(blank=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"
    
class FriendRequest(models.Model):
    sender = models.ForeignKey(User, related_name='sent_requests', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_requests', on_delete=models.CASCADE, null=True)  
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.sender} -> {self.receiver}"
    
class Friendship(models.Model):
    user1 = models.ForeignKey(User, related_name='friend1', on_delete=models.CASCADE)
    user2 = models.ForeignKey(User, related_name='friend2', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user1.username} is friends with {self.user2.username}"
    
    
class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Message from {self.sender} to {self.receiver}'


class Card(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cards")  # To associate cards with users
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='card_images/', null=True, blank=True)  # Store images in the 'card_images/' directory
    description = models.TextField()

    def __str__(self):
        return self.title

SocialMedia/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import UserRegistrationForm, SignUpForm, PostForm, CommentForm, ProfileForm, UsernameForm, PronounsForm, BioForm, UserUpdateForm, CardForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from .models import FriendRequest, Friendship, Post, Comment, Profile, Bookmark, Card
from django.shortcuts import redirect, get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.template.loader import render_to_string
import logging


@login_required
def home(request):
    friendships = request.user.friend1.all() | request.user.friend2.all()
    friends = list(set(friendship.user2 if friendship.user1 == request.user else friendship.user1 for friendship in friendships))
    posts = Post.objects.filter(is_short=False)

    for post in posts:
        post.comments_list = post.comments.all() 

    if 'id' in request.GET:
        post_id = request.GET['id']
        post = get_object_or_404(Post, id=post_id)
        return render(request, 'post_detail.html', {'post': post})
    else:
        # Default behavior (e.g. showing the post list on home)
        posts = Post.objects.all()

    return render(request, 'Index/index.html', {'posts': posts, 'friends': friends})



def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Invalid username or password.")  # Add an error message
    return render(request, 'registration/login.html')


def user_logout(request):
    logout(request)
    return redirect('login')  # Redirect to the login page after logout

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)  # Use SignUpForm here
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])  # Set the password after hashing
            user.save()

            # Log the user in after registration
            login(request, user)

            messages.success(request, 'Account created and logged in successfully!')  # Success message
            return redirect('home')  # Redirect to homepage after successful sign-up and login
    else:
        form = SignUpForm()  # Use SignUpForm here
    
    # Return the response with the form context
    return render(request, 'registration/signup.html', {'form': form})




# sending friend request


@login_required
def send_friend_request(request, user_id):
    receiver = get_object_or_404(User, id=user_id)
    FriendRequest.objects.create(sender=request.user, receiver=receiver)
    # return JsonResponse({'success': True})






# accepting friend request


@login_required
def accept_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    Friendship.objects.create(user1=friend_request.sender, user2=friend_request.receiver)
    friend_request.delete()
    return JsonResponse({'success': True})






# rejecting friend request


@login_required
def reject_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    friend_request.delete()
    return JsonResponse({'success': True})




# friend requests page
@login_required
def friend_requests(request):
    requests = FriendRequest.objects.filter(receiver=request.user)
    return render(request, 'Friend_Request/friend_requests.html', {'friend_requests': requests})



@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("home")
        
    else:
        form = PostForm()

    return render (request, 'create_post.html', {"form":form})


# VIEW TO ADD A COMMENT

@login_required
def add_comment(request, post_id):
    if request.method == 'POST':
        name = request.POST.get('name')
        body = request.POST.get('body')
        comment = Comment.objects.create(post_id=post_id, name=name, body=body)
        return JsonResponse({
            'success': True,
            'name': comment.name,
            'body': comment.body,
            'date_added': comment.date_added.strftime("%Y-%m-%d %H:%M:%S"),
        })


# view for profile picture submission

@login_required
def update_profile(request, username):
    user = get_object_or_404(User, username=username)

    if request.method == "POST":
        # Handle the forms
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)  # Ensure request.FILES is passed

        if profile_form.is_valid():
            profile_form.save()  # Update profile (profile_picture, bio, etc.)
            messages.success(request, f'{user.username}, your profile has been updated.')
            return redirect('profile_view', username=user.username)
        else:
            messages.error(request, 'There was an error updating your profile. Please try again.')
    else:
        # If GET request, create empty form instances
        profile_form = ProfileForm(instance=user.profile)

    context = {
        "profile_form": profile_form,
        "user": user
    }

    return render(request, 'update_profile.html', context)

# @login_required(login_url='login')
# def profile_view(request, username):
#     user = get_object_or_404(User, username=username)
#     return render(request, 'profile.html', {'user': user})




@login_required
def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    posts_count = user.posts.count()  # Count the user's posts
    friendships = Friendship.objects.filter(user1=user) | Friendship.objects.filter(user2=user)
    friends = list(set(friendship.user2 if friendship.user1 == user else friendship.user1 for friendship in friendships))
    friends_count = len(friends)
    profile_user = get_object_or_404(User, username=username)

    context = {
        'user': user,
        'posts_count': posts_count,
        'friends_count': friends_count,
        'profile_user': profile_user,  # Ensure the correct profile_user is passed
    }
    return render(request, 'profile.html', context)



@login_required
def user_logout(request):
    logout(request)
    return render(request, 'logout.html')


def delete_post(request, post_id):
    if request.method == "POST":
        try:
            post = Post.objects.get(id=post_id, author=request.user)
            post.delete()
            return JsonResponse({'success': True})
        except Post.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Post not found.'}, status=404)
    return JsonResponse({'success': False}, status=400)

def update_username(request, username):
    user = get_object_or_404(User, username=username)
    if request.method == 'POST':
        form = UsernameForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('profile_view', username=user.username)
    else:
        form = UsernameForm(instance=user)
    return render(request, 'update_username.html', {'form': form})

def update_pronouns(request, username):
    user = get_object_or_404(User, username=username)
    if request.method == 'POST':
        form = PronounsForm(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile_view', username=user.username)
    else:
        form = PronounsForm(instance=user.profile)
    return render(request, 'update_pronouns.html', {'form': form})

def update_bio(request, username):
    user = get_object_or_404(User, username=username)
    if request.method == 'POST':
        form = BioForm(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile_view', username=user.username)
    else:
        form = BioForm(instance=user.profile)
    return render(request, 'update_bio.html', {'form': form})



@require_http_methods(["DELETE"])
def unfriend_view(request, user_id):
    friendship = Friendship.objects.filter(
        (Q(user1=request.user) & Q(user2_id=user_id)) |
        (Q(user1_id=user_id) & Q(user2=request.user))
    ).first()

    if friendship:
        friendship.delete()
        return JsonResponse({'message': 'Unfriended successfully.'}, status=200)
    else:
        return JsonResponse({'error': 'Friendship does not exist.'}, status=404)



@login_required
def friends_view(request):
    friendships = Friendship.objects.filter(user1=request.user) | Friendship.objects.filter(user2=request.user)
    friends = []

    for friendship in friendships:
        if friendship.user1 == request.user:
            friends.append(friendship.user2)
        else:
            friends.append(friendship.user1)

    return render(request, 'friends.html', {'friends': friends})


@login_required

SocialMedia/templates/bookmarks.html
<!-- bookmarks.html -->
{% extends "Index/index.html" %}

{% block content %}
    <h2>Your Bookmarked Posts</h2>
    
    {% if bookmarked_posts %}
        <ul>
            {% for bookmark in bookmarked_posts %}
                <li>
                    <a href="{% url 'post_detail' bookmark.post.id %}">{{ bookmark.post.title }}</a>
                    <span>Bookmarked on {{ bookmark.created_at }}</span>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have no bookmarked posts yet.</p>
    {% endif %}
{% endblock %}

SocialMedia/templates/create_card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Your 3D Card</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="container">
        <h2>Create Your Own 3D Card</h2>

        <!-- Form to create the card -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="title" placeholder="Enter Card Title" required>
            <textarea name="description" placeholder="Enter Description" required></textarea>
            <input type="file" name="image" accept="image/*" required>
            <input type="file" name="background_image" accept="image/*">
            <input type="file" name="cutout_image" accept="image/*">
            <button type="submit">Create Card</button>
        </form>

        <a href="{% url 'user_cards' %}">View Your Cards</a>
    </div>
</body>
</html>

SocialMedia/templates/update_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- <link rel="stylesheet" href="{% static 'css/index.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/dark-mode.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@300..900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        :root {
            --primary-color: #007bff;
            --primary-hover: #0056b3;
            --success-color: #28a745;
            --success-hover: #218838;
            --light-gray: lightgray;
            --background-color: #f8f9fa;
            --container-bg: white;
            --text-color: #555;
        }

        html, body {
            height: 150%;
            width: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            background-color: var(--background-color);
            font-family: "Poppins", sans-serif;
        }

        .container {
            width: 100%;
            max-width: 800px;
            padding: 2em;
            background-color: var(--container-bg);
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            margin: 2em 0;
        }

        h1 {
            font-size: 2.5em;
            font-weight: bold;
            margin-bottom: 1em;
            text-align: center;
        }

        .profile-pic {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            margin-bottom: 1em;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .change-btn {
            background-color: var(--primary-color);
            color: white;
            border: none;
            padding: 0.5em;
            border-radius: 5px;
            cursor: pointer;
            font-size: 1em;
            text-decoration: none;
            display: block;
            width: 90%;
            margin: 1em 2em;
            text-align: center;
        }

        .change-btn:hover {
            background-color: var(--primary-hover);
        }

        .profile-info {
            width: 100%;
            margin-top: 2em;
        }

        .info-row {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1em;
    border-bottom: 1px solid var(--light-gray);
    background-color: var(--container-bg);
    margin-bottom: 1em;
    width: 100%;
}

.info-row label {
    margin: 0 0 0.5em 0;
    font-size: 1em;
    width: 100%;
    text-align: center;
}

.info-row input,
.info-row textarea {
    width: 90%;
    padding: 10px;
    border: 1px solid var(--light-gray);
    border-radius: 5px;
    font-size: 1em;
    text-align: center;
}
        .info-row textarea {
            height: 50px;
            resize: none;
        }

        .edit-btn {
            background-color: var(--success-color);
            color: white;
            padding: 0.5em 2em;
            border-radius: 5px;
            text-decoration: none;
            display: block;
            width: 100%;
            margin: 1em 0;
            border: none;
        }

        .edit-btn:hover {
            background-color: var(--success-hover);
        }

        .form-fields {
            display: none;
            margin-top: 1em;
        }

        .form-fields.active {
            display: block;
        }

        .profile-picture-input {
            display: flex;
            align-items: center;
        }

        .current-profile-pic-wrapper {
            margin-right: 1em;
        }

        .current-profile-pic {
            width: 80px;
            height: 80px;
            border-radius: 50%;
            object-fit: cover;
            border: 1px solid var(--light-gray);
        }

        .picture-info {
            display: flex;
            flex-direction: column;
        }

        .picture-info p {
            margin: 0;
            font-size: 0.9em;
            color: var(--text-color);
        }

        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1em;
            background-color: #cacaca;
            width: 100vw;
            position: fixed;
            left: 0;
            top: 0;
            z-index: 10;
            height: 3em;
            font-family: "Sansita Swashed", system-ui;
            margin: 0;
        }

        .nav-items {
            display: flex;
            font-size: 1.3rem;
            flex-grow: 1;
        }

        .nav-list {
            list-style-type: none;
            padding: 0;
            margin: 0;
            display: flex;
            flex-grow: 1;
            justify-content: flex-start;
        }

        .nav-list li {
            margin-right: 1.5em;
        }

        .app-name {
            flex-grow: 1;
            text-align: center;
            font-family: "Sansita Swashed", system-ui;
            color: black;
            font-size: 2rem;
            margin-right: 17em;
        }
    
        body.dark-mode {
            background-color: #121212;
            color: white;
        }

        body.dark-mode .navbar {
            background-color: #333;
        }

        body.dark-mode .navbar i {
            color: white;
        }

        body.dark-mode .container {
            background-color: #2c2f34;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
        }

        body.dark-mode h1 {
            color: white;
        }

        body.dark-mode .profile-pic {
            border: 3px solid #444;
        }

        body.dark-mode .change-btn {
            background-color: #444;
            color: white;
            margin-right: 1em;
        }

        body.dark-mode .change-btn:hover {
            background-color: #555;
        }

        body.dark-mode .edit-btn {
            background-color: #28a745;
        }

        body.dark-mode .edit-btn:hover {
            background-color: #218838;
        }

        body.dark-mode .info-row {
            border-bottom: 1px solid #444;
        }

        body.dark-mode .info-row input,
        body.dark-mode .info-row textarea {
            background-color: #333;
            color: white;
            border: 1px solid #444;
        }

        body.dark-mode .navbar {
            background-color: #333;
        }

        body.dark-mode .navbar .app-name h3 {
            color: white;
        }
    </style>
</head>

<body>

    <div id="preloader" style="
    background: #fff url(../media/loader.gif) no-repeat center center;
    height: 105vh;
    width: 100%;
    position: fixed;
    z-index: 1000;
    "></div>

    <!-- NAVBAR -->
    <nav class="navbar">
        <div class="hamburger" onclick="toggleMenu()">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>
        <div class="nav-items">
            <div class="close-icon" onclick="toggleMenu()">
                <div class="bar top"></div>
                <div class="bar bottom"></div>
            </div>
            <ul class="nav-list">
                <li>
                    <a href="{% url 'home' %}" style="text-decoration: none; color: inherit;">
                        <i class="fa-solid fa-house"></i>
                    </a>
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a href="{% url 'profile_view' user.username %}" style="text-decoration: none; color: inherit;">
                        <i class="fa-solid fa-user"></i>
                    </a>
                    {% endif %}
                </li>
                <li>
                    <a href="{% url 'messages' %}" style="text-decoration: none; color: inherit;">
                        <i class="fa-solid fa-message"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'friends' %}" style="text-decoration: none; color: inherit;">
                        <i class="fa-solid fa-user-friends"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'create_post' %}" style="text-decoration: none; color: inherit;">
                        <i class="fa-solid fa-plus"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'shorts_view' %}" style="text-decoration: none; color: inherit;">
                        <i class="fa-brands fa-tiktok"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="app-name">
            <h3>Amity</h3>
        </div>
    </nav>
    <!-- END OF NAVBAR -->

    <div class="container" style="margin-top: 5em;">
        <h1>Edit Profile</h1>
        
        <!-- Display current profile picture -->
        {% if user.profile.profile_picture %}
            <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" class="profile-pic">
        {% else %}
            <img src="{% static 'images/default-profile.png' %}" alt="Default Profile Picture" class="friend-pic">
        {% endif %}
    
        <!-- Trigger file input for changing profile picture -->
        <a href="#" class="change-btn" onclick="document.getElementById('profile-picture-input').click(); return false;">Change Profile Picture</a>
    
        <button class="edit-btn" onclick="toggleFields()">Edit Information</button>
    
        <div class="form-fields" id="form-fields">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="profile-info">
                    <!-- Pronouns field -->
                    <div class="info-row">
                        <label for="id_pronouns">Pronouns</label>
                        {{ profile_form.pronouns }}
                    </div>
                    
                    <!-- Bio field -->
                    <div class="info-row">
                        <label for="id_bio">Bio</label>
                        <textarea class="bio-input" name="bio" id="bio" rows="3">{{ profile_form.bio.value|default:'' }}</textarea>
                    </div>
    
                    <!-- Profile picture field -->
                    <div class="info-row">
                        <label for="id_profile_picture">Profile Picture</label>
                        <div class="profile-picture-input">
                            <div class="current-profile-pic-wrapper">
                                {% if user.profile.profile_picture %}
                                    <img src="{{ user.profile.profile_picture.url }}" alt="Current Profile Picture" class="current-profile-pic">
                                {% else %}
                                    <img src="{% static 'profile_pics/default-profile.png' %}" alt="Default Profile Picture" class="current-profile-pic">
                                {% endif %}
                            </div>
                            <div class="picture-info">
                                <p>Currently: {{ user.profile.profile_picture.name }}</p>
                                <!-- Hidden file input for uploading new profile picture -->
                                {{ profile_form.profile_picture }}
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Submit button -->
                <button type="submit" class="edit-btn">Save Changes</button>
            </form>
        </div>
    </div>
    
    <script>
        function toggleFields() {
            const formFields = document.getElementById('form-fields');
            formFields.classList.toggle('active');
        }
    </script>
    

    <script>
        var loader = document.getElementById("preloader");
        window.addEventListener('load', function () {
            setTimeout(function () {
                loader.style.display = "none";
            }, 1000);
        });
    </script>
    <script src="{% static 'js/dark-mode.js' %}" defer></script>
</body>

</html>